apiVersion: apps/v1
kind: Deployment
metadata:
    name: entry-server-deployment
    labels:
        app: entry-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: entry-server
    template:
        metadata:
            labels:
                app: entry-server
        spec:
            containers:
                - name: entry-server
                  image: 'fedesin31/entry-server:latest'
                  ports:
                      - containerPort: 5000
                  env:
                      - name: SPLIT_SERVICE_URL
                        valueFrom:
                            configMapKeyRef:
                                name: application-config
                                key: SPLIT_SERVICE_URL
                      - name: BUCKET_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: application-config
                                key: BUCKET_NAME
                      - name: CREDENTIALS_PATH
                        value: /credentials/credentials.json
                  volumeMounts:
                      - name: credentials-volume
                        mountPath: /credentials
                        readOnly: true
            volumes:
                - name: credentials-volume
                  configMap:
                      name: credentials-config
