apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq
spec:
    image: rabbitmq:3.13-management
    service:
        type: LoadBalancer
    # Agrega toleration para asegurar que los pods se creen unicamente en el node group de servicios
    tolerations:
        - key: instance_type
          operator: NotEqual
          value: services
          effect: NoSchedule
