apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
    name: rabbitmq
    namespace: rabbitmq-namespace
spec:
    image: rabbitmq:3.13-management
    service:
        type: LoadBalancer
    replicas: 3
    resources:
        requests:
            memory: '1Gi'
            cpu: '500m'
        limits:
            memory: '2Gi'
            cpu: '1'
    policies:
        - name: sobel-mirror
          vhost: /
          pattern: .*sobel.*
          definition: '{"ha-mode":"all"}'
          priority: 0
