version: '3.8'
services:
    redis:
        container_name: redis
        image: redis:alpine3.19
        restart: always
        ports:
            - '6379:6379'
        volumes:
            - ./redis:/data
        networks:
            - sobel-network
    entry-server:
        container_name: entry-server
        image: entry-server
        ports:
            - '5001:5000'
        environment:
            - SPLIT_SERVICE_URL=${SPLIT_SERVICE_URL}
        networks:
            - sobel-network
    split-service:
        depends_on:
            - redis
            - entry-server
        container_name: split-service
        image: split-service
        ports:
            - '5000'
        environment:
            - FRAGMENTS_COUNT=${FRAGMENTS_COUNT}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
        networks:
            - sobel-network
networks:
    sobel-network:
