name: Workflow for HIT 3 - TP 3

on:
    push:
        branches: ['main']
        paths: ['TP4/ej3/**']
jobs:
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./TP4/ej3/sobel-service
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sobel-service:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./TP4/ej3/split-service
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/split-service:latest

            # - name: Build and push Docker image
            #   uses: docker/build-push-action@v2
            #   with:
            #       context: ./TP4/ej3/join-service
            #       push: true
            #       tags: ${{ secrets.DOCKER_HUB_USERNAME }}/join-service:latest
