name: Workflow for HIT 6 - TP 1

on:
    push:
        branches: ['main']
        paths: ['TP1/ej6/**']
jobs:
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./TP1/ej6/client-server
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/client-serverej6:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./TP1/ej6/contact-server
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/serverej6:latest
