name: Workflow for Sobel - TP 2

on:
    push:
        branches: ['main']
        paths: ['TP4/ej1/']
jobs:
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./TP4/ej1/parte1
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp4-ej1-sobel:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./TP4/ej1/parte2
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp4-ej1-splitter:latest
